// <auto-generated />
using System;
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(LeaderboardDbContext))]
    [Migration("20251009040908_AddGetPlayRankProc")]
    partial class AddGetPlayRankProc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Model.Player", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastSubmitDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Score")
                        .IsDescending();

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastSubmitDate = new DateTime(2025, 10, 8, 12, 0, 0, 0, DateTimeKind.Utc),
                            Score = 1200
                        },
                        new
                        {
                            Id = 2,
                            LastSubmitDate = new DateTime(2025, 10, 8, 12, 0, 0, 0, DateTimeKind.Utc),
                            Score = 900
                        },
                        new
                        {
                            Id = 3,
                            LastSubmitDate = new DateTime(2025, 10, 8, 12, 0, 0, 0, DateTimeKind.Utc),
                            Score = 1200
                        },
                        new
                        {
                            Id = 4,
                            LastSubmitDate = new DateTime(2025, 10, 8, 12, 0, 0, 0, DateTimeKind.Utc),
                            Score = 1450
                        },
                        new
                        {
                            Id = 5,
                            LastSubmitDate = new DateTime(2025, 10, 8, 12, 0, 0, 0, DateTimeKind.Utc),
                            Score = 1500
                        },
                        new
                        {
                            Id = 6,
                            LastSubmitDate = new DateTime(2025, 10, 8, 12, 0, 0, 0, DateTimeKind.Utc),
                            Score = 1700
                        },
                        new
                        {
                            Id = 7,
                            LastSubmitDate = new DateTime(2025, 10, 8, 12, 0, 0, 0, DateTimeKind.Utc),
                            Score = 450
                        },
                        new
                        {
                            Id = 8,
                            LastSubmitDate = new DateTime(2025, 10, 8, 12, 0, 0, 0, DateTimeKind.Utc),
                            Score = 980
                        },
                        new
                        {
                            Id = 9,
                            LastSubmitDate = new DateTime(2025, 10, 8, 12, 0, 0, 0, DateTimeKind.Utc),
                            Score = 1010
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
